### ISSUE TITLE
Path opcional em métodos

### ISSUE THREAD

**Issue by gmcoringa** [ljtfreitas/java-restify#1]
Quando uma interface possuir a anotação ``Path``, anotar os métodos com o mesmo poderia ser opcional, sendo assim considerando apenas o path da interface. Exemplo:

```java
@Path("/my/api/{pathParam}/context")
public interface MyApi {

    @Get
    List<MyObject> listMyObjects(@PathParameter pathParam, @QueryParameter queryParam);
}
```

**Comment by ljtfreitas** [comment]
Na verdade, esse funcionamento é mesmo proposital. O java-restify assume que cada método declarado da interface representa uma operação específica de uma API, de modo que cada método representaria uma requisição para um endpoint específico (de modo equivalente aos frameworks server side, como Spring MVC, VRaptor, JAX-RS, etc, onde normalmente cada método público representa um endpoint diferente).

Por esse motivo, a anotação `@Path` é obrigatória no nível do método.
