### ISSUE TITLE
Tratamento de parâmetros nulos para QueryParameter

### ISSUE THREAD

**Issue by gmcoringa** [ljtfreitas/java-restify#2]
Quaisquer ``QueryParameter`` nulos causam NPE. Seria interessante que fossem opcionais, evitando assim NPE.

Talvez fosse interessante adicionar um atributo ao ``QueryParameter`` para indicar quando um parâmetro não é opcional.

**Comment by ljtfreitas** [comment]
Corrigido no pull request https://github.com/ljtfreitas/java-restify/pull/3. Obrigado!
