### ISSUE TITLE
EndpointRequest no EndpointResponseErrorFallback

### ISSUE THREAD

**Issue by gmcoringa** [ljtfreitas/java-restify#4]
Seria interessante ter uma interface handler do lifecycle da request com os seguintes métodos:

* ``beforeSendRequest(request)``
* ``afterSendRequest(request, response)``
* ``onError(request, throwable)``

**Comment by ljtfreitas** [comment]
Na versão 2.x a interface `HttpClientRequestInterceptor` atende esse propósito. :wink:

@ljtfreitas
